/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: YukiTori (https://sketchfab.com/yukitori)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/stone-toy-ca44244d6234400089dc987fab952204
title: Stone Toy 🗿
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/toy-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.StoneToy_Body_01_lambert1_0.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.StoneToy_Body_01_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
          <mesh geometry={nodes.StoneToy_Tooth_1_01_lambert1_0.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.StoneToy_Tooth_2_01_lambert1_0.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.StoneToy_Tooth_3_01_lambert1_0.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.polySurface3_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
          <mesh geometry={nodes.polySurface4_lambert1_0.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.polySurface1_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
          <mesh geometry={nodes.polySurface2_lambert1_0.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.StoneToy_stone_1_01_lambert1_0.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.StoneToy_stone_2_01_lambert1_0.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.StoneToy_stone_3_01_lambert1_0.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.StoneToy_stone_4_01_lambert1_0.geometry} material={materials.lambert1} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/toy-transformed.glb')
